### ISSUE TITLE
[SHOULD] Repo topics

### ISSUE THREAD

**Issue by jason-fox** [ging/fiware-cosmos-orion-flink-connector#7]
Please click the edit button at the head of the repo and add the  topics as shown (or similar):

### Topics

`fiware`, `fiware-cosmos`, `processing` ... and any other relevant tags ( e.g. `flink`)

- SHOULD requirement from the TSC.

**Comment by sonsoleslp** [comment]
Done! I'll close the issue. Thank you, Jason.
